# Application name
spring.application.name=Recipesdemo

# Server port (defaults to 8080 if not set)
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/fiesta?serverTimezone=UTC&createDatabaseIfNotExists=true
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#intercation between spring and mysql server
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

# JWT secret (Replace with a strong secret in production)
jwt.secret=jkfksdjfkjsdf92398JKASKJDKJsdh1h3jhdhd

# Logging Level
logging.level.org.springframework=INFO
logging.level.com.example=DEBUG
